[api_keys]
GEMINI_API_KEY = "AIzaSyAXalBlNFOwzQDMIJBIG87UD7xCobgaRPA"
MONGODB_URI = "mongodb+srv://DavidRocha:davidoscar@capstone.9ajag.mongodb.net/?retryWrites=true&w=majority&appName=Capstone"
MONGODB_NAME = "jobsDB"
MONGODB_JOBS_COLLECTION = "jobsCollection"